# coding: utf-8

"""
    Channel Manager Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from channelmanager.api.channel_manager_api import ChannelManagerApi


class TestChannelManagerApi(unittest.TestCase):
    """ChannelManagerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChannelManagerApi()

    def tearDown(self) -> None:
        pass

    def test_channel_manager_create_association(self) -> None:
        """Test case for channel_manager_create_association

        CreateAssociation
        """
        pass

    def test_channel_manager_create_channel(self) -> None:
        """Test case for channel_manager_create_channel

        CreateChannel
        """
        pass

    def test_channel_manager_create_market(self) -> None:
        """Test case for channel_manager_create_market

        CreateMarket
        """
        pass

    def test_channel_manager_delete_association(self) -> None:
        """Test case for channel_manager_delete_association

        DeleteAssociation
        """
        pass

    def test_channel_manager_delete_channel(self) -> None:
        """Test case for channel_manager_delete_channel

        DeleteChannel
        """
        pass

    def test_channel_manager_delete_market(self) -> None:
        """Test case for channel_manager_delete_market

        DeleteMarket
        """
        pass

    def test_channel_manager_get_channel(self) -> None:
        """Test case for channel_manager_get_channel

        GetChannel
        """
        pass

    def test_channel_manager_get_channel_with_associations(self) -> None:
        """Test case for channel_manager_get_channel_with_associations

        GetChannelWithAssociations
        """
        pass

    def test_channel_manager_get_market(self) -> None:
        """Test case for channel_manager_get_market

        GetMarket
        """
        pass

    def test_channel_manager_get_market_with_associations(self) -> None:
        """Test case for channel_manager_get_market_with_associations

        GetMarketWithAssociations
        """
        pass

    def test_channel_manager_list_channels(self) -> None:
        """Test case for channel_manager_list_channels

        ListChannels
        """
        pass

    def test_channel_manager_list_channels_with_associations(self) -> None:
        """Test case for channel_manager_list_channels_with_associations

        ListChannelsWithAssociations
        """
        pass

    def test_channel_manager_list_markets(self) -> None:
        """Test case for channel_manager_list_markets

        ListMarkets
        """
        pass

    def test_channel_manager_list_markets_with_associations(self) -> None:
        """Test case for channel_manager_list_markets_with_associations

        ListMarketsWithAssociations
        """
        pass

    def test_channel_manager_update_channel(self) -> None:
        """Test case for channel_manager_update_channel

        UpdateChannel
        """
        pass

    def test_channel_manager_update_market(self) -> None:
        """Test case for channel_manager_update_market

        UpdateMarket
        """
        pass


if __name__ == '__main__':
    unittest.main()
