# coding: utf-8

"""
    Channel Manager Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from channelmanager.models.channelmanager_list_channels_request import ChannelmanagerListChannelsRequest

class TestChannelmanagerListChannelsRequest(unittest.TestCase):
    """ChannelmanagerListChannelsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChannelmanagerListChannelsRequest:
        """Test ChannelmanagerListChannelsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChannelmanagerListChannelsRequest`
        """
        model = ChannelmanagerListChannelsRequest()
        if include_optional:
            return ChannelmanagerListChannelsRequest(
                tenant_id = '',
                page_size = 56,
                page_token = ''
            )
        else:
            return ChannelmanagerListChannelsRequest(
                tenant_id = '',
        )
        """

    def testChannelmanagerListChannelsRequest(self):
        """Test ChannelmanagerListChannelsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
