# coding: utf-8

"""
    Channel Manager Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from channelmanager.models.channelmanager_delete_association_request import ChannelmanagerDeleteAssociationRequest

class TestChannelmanagerDeleteAssociationRequest(unittest.TestCase):
    """ChannelmanagerDeleteAssociationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChannelmanagerDeleteAssociationRequest:
        """Test ChannelmanagerDeleteAssociationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChannelmanagerDeleteAssociationRequest`
        """
        model = ChannelmanagerDeleteAssociationRequest()
        if include_optional:
            return ChannelmanagerDeleteAssociationRequest(
                tenant_id = '',
                id = ''
            )
        else:
            return ChannelmanagerDeleteAssociationRequest(
        )
        """

    def testChannelmanagerDeleteAssociationRequest(self):
        """Test ChannelmanagerDeleteAssociationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
