# coding: utf-8

"""
    Channel Manager Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from channelmanager.models.channelmanager_channel_status import ChannelmanagerChannelStatus

class TestChannelmanagerChannelStatus(unittest.TestCase):
    """ChannelmanagerChannelStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelmanagerChannelStatus(self):
        """Test ChannelmanagerChannelStatus"""
        # inst = ChannelmanagerChannelStatus()

if __name__ == '__main__':
    unittest.main()
