# coding: utf-8

"""
    Channel Manager Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from channelmanager.models.channelmanager_update_market_request_payload import ChannelmanagerUpdateMarketRequestPayload

class TestChannelmanagerUpdateMarketRequestPayload(unittest.TestCase):
    """ChannelmanagerUpdateMarketRequestPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChannelmanagerUpdateMarketRequestPayload:
        """Test ChannelmanagerUpdateMarketRequestPayload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChannelmanagerUpdateMarketRequestPayload`
        """
        model = ChannelmanagerUpdateMarketRequestPayload()
        if include_optional:
            return ChannelmanagerUpdateMarketRequestPayload(
                name = '',
                description = '',
                countries = [
                    'COUNTRY_CODE_UNKNOWN'
                    ]
            )
        else:
            return ChannelmanagerUpdateMarketRequestPayload(
        )
        """

    def testChannelmanagerUpdateMarketRequestPayload(self):
        """Test ChannelmanagerUpdateMarketRequestPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
