# coding: utf-8

"""
    Channel Manager Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from channelmanager.models.channelmanager_create_channel_request import ChannelmanagerCreateChannelRequest

class TestChannelmanagerCreateChannelRequest(unittest.TestCase):
    """ChannelmanagerCreateChannelRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChannelmanagerCreateChannelRequest:
        """Test ChannelmanagerCreateChannelRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChannelmanagerCreateChannelRequest`
        """
        model = ChannelmanagerCreateChannelRequest()
        if include_optional:
            return ChannelmanagerCreateChannelRequest(
                tenant_id = '',
                code = '',
                image = '',
                name = '',
                default_language = 'LANGUAGE_CODE_UNKNOWN',
                settings = channelmanager.models.channelmanager_channel_settings.channelmanagerChannelSettings(
                    hide_oos_products = True, 
                    hide_priceless_products = True, ),
                website = channelmanager.models.channelmanager_channel_type_website.channelmanagerChannelTypeWebsite(
                    domain = '', ),
                status = 'CH_STATUS_UNKNOWN'
            )
        else:
            return ChannelmanagerCreateChannelRequest(
                tenant_id = '',
                code = '',
                name = '',
        )
        """

    def testChannelmanagerCreateChannelRequest(self):
        """Test ChannelmanagerCreateChannelRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
