# coding: utf-8

"""
    Channel Manager Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from channelmanager.models.channelmanager_country_code import ChannelmanagerCountryCode

class TestChannelmanagerCountryCode(unittest.TestCase):
    """ChannelmanagerCountryCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelmanagerCountryCode(self):
        """Test ChannelmanagerCountryCode"""
        # inst = ChannelmanagerCountryCode()

if __name__ == '__main__':
    unittest.main()
