# coding: utf-8

"""
    Channel Manager Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from channelmanager.models.channelmanager_update_channel_request_payload import ChannelmanagerUpdateChannelRequestPayload

class TestChannelmanagerUpdateChannelRequestPayload(unittest.TestCase):
    """ChannelmanagerUpdateChannelRequestPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChannelmanagerUpdateChannelRequestPayload:
        """Test ChannelmanagerUpdateChannelRequestPayload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChannelmanagerUpdateChannelRequestPayload`
        """
        model = ChannelmanagerUpdateChannelRequestPayload()
        if include_optional:
            return ChannelmanagerUpdateChannelRequestPayload(
                image = '',
                name = '',
                default_language = 'LANGUAGE_CODE_UNKNOWN',
                settings = channelmanager.models.channelmanager_channel_settings.channelmanagerChannelSettings(
                    hide_oos_products = True, 
                    hide_priceless_products = True, ),
                website = channelmanager.models.channelmanager_channel_type_website.channelmanagerChannelTypeWebsite(
                    domain = '', ),
                status = 'CH_STATUS_UNKNOWN'
            )
        else:
            return ChannelmanagerUpdateChannelRequestPayload(
        )
        """

    def testChannelmanagerUpdateChannelRequestPayload(self):
        """Test ChannelmanagerUpdateChannelRequestPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
