# coding: utf-8

"""
    Channel Manager Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from channelmanager.models.channelmanager_list_markets_request import ChannelmanagerListMarketsRequest

class TestChannelmanagerListMarketsRequest(unittest.TestCase):
    """ChannelmanagerListMarketsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChannelmanagerListMarketsRequest:
        """Test ChannelmanagerListMarketsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChannelmanagerListMarketsRequest`
        """
        model = ChannelmanagerListMarketsRequest()
        if include_optional:
            return ChannelmanagerListMarketsRequest(
                tenant_id = '',
                page_size = 56,
                page_token = ''
            )
        else:
            return ChannelmanagerListMarketsRequest(
        )
        """

    def testChannelmanagerListMarketsRequest(self):
        """Test ChannelmanagerListMarketsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
