# coding: utf-8

"""
    Channel Manager Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from channelmanager.models.channelmanager_channel_settings import ChannelmanagerChannelSettings
from channelmanager.models.channelmanager_channel_status import ChannelmanagerChannelStatus
from channelmanager.models.channelmanager_channel_type_website import ChannelmanagerChannelTypeWebsite
from channelmanager.models.channelmanager_language_code import ChannelmanagerLanguageCode
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ChannelmanagerUpdateChannelRequestPayload(BaseModel):
    """
    ChannelmanagerUpdateChannelRequestPayload
    """ # noqa: E501
    image: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    default_language: Optional[ChannelmanagerLanguageCode] = Field(default=None, alias="defaultLanguage")
    settings: Optional[ChannelmanagerChannelSettings] = None
    website: Optional[ChannelmanagerChannelTypeWebsite] = None
    status: Optional[ChannelmanagerChannelStatus] = None
    __properties: ClassVar[List[str]] = ["image", "name", "defaultLanguage", "settings", "website", "status"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ChannelmanagerUpdateChannelRequestPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of settings
        if self.settings:
            _dict['settings'] = self.settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of website
        if self.website:
            _dict['website'] = self.website.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ChannelmanagerUpdateChannelRequestPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "image": obj.get("image"),
            "name": obj.get("name"),
            "defaultLanguage": obj.get("defaultLanguage"),
            "settings": ChannelmanagerChannelSettings.from_dict(obj.get("settings")) if obj.get("settings") is not None else None,
            "website": ChannelmanagerChannelTypeWebsite.from_dict(obj.get("website")) if obj.get("website") is not None else None,
            "status": obj.get("status")
        })
        return _obj


